source 'https://rubygems.org'

# Specify your gem's dependencies in example_service.gemspec
gemspec

# gem 'eventmachine'
gem 'em-http-server'
gem 'service_kit', path: "../"
gem 'example_service-contract', path: "./lib/example_service-contract"

gem 'puma', '~> 2.16.0'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma-stats-logger'
